あたらしく作ったファイル

スタッシュ2回目
GitHubで追記
fetch merge したあとに stash apply
同じ行への修正がリモートリポジトリにあったのでコンフリクトした

